PREFIX gs: <ips://galacteek.ld/>
PREFIX h: <ips://galacteek.ld/Hashmark#>
PREFIX rprefs: <ips://galacteek.ld/ResourcePreferences#>

SELECT ?uri ?descr ?title
       ?comment
       ?schemePreferred
       ?iconUrl ?icon
       ?mimeType ?mimeCategory ?dateCreated
       ?prefsWebProfile
       ?prefsSchemePreferred
       ?prefsInQuickAccessDock
WHERE {
  ?uri a gs:Hashmark .
  ?uri h:title ?title .

  OPTIONAL { ?uri h:dateCreated ?dateCreated . } .
  OPTIONAL {
    ?uri h:description ?descr .
    FILTER (langMatches(lang(?descr), str(?langTagMatch)) )
  } .
  OPTIONAL {
    ?uri h:comment ?comment .
    FILTER (langMatches(lang(?comment), str(?langTagMatch)) )
  } .

  OPTIONAL { ?uri h:category ?category . } .
  OPTIONAL { ?uri h:mimeType ?mimeType . } .
  OPTIONAL { ?uri h:mimeCategory ?mimeCategory . } .
  OPTIONAL { ?uri h:schemePreferred ?schemePreferred . } .
  OPTIONAL { ?uri gs:url ?url . } .

  # Resource preferences
  ?uri h:resourcePrefs ?prefs .
  ?prefs rprefs:inQuickAccessDock ?prefsInQuickAccessDock .

  OPTIONAL {
    ?prefs rprefs:useWebProfile ?prefsWebProfile .
    ?prefs rprefs:schemePreferred ?prefsSchemePreferred .
  } .

  # Icon
  OPTIONAL { 
    ?uri gs:icon ?icon .
    ?icon gs:contentUrl ?iconUrl .
  } .

  # Thumbnail
  OPTIONAL { 
    ?uri gs:thumbnail ?icon .
    ?icon gs:contentUrl ?thumbnailUrl .
  } .

  FILTER (?prefsInQuickAccessDock = ?inQADock)
  FILTER (langMatches(lang(?title), str(?langTagMatch)) )


}

GROUP BY ?uri
ORDER BY DESC(?dateCreated)
