PREFIX gs: <ips://galacteek.ld/>
PREFIX h: <ips://galacteek.ld/Hashmark#>
PREFIX tag: <ips://galacteek.ld/Tag#>

SELECT *
WHERE {
  ?uri a gs:Hashmark .
  ?uri h:tag ?taguri .

  ?uri h:title ?title .
  ?uri h:description ?descr .

  OPTIONAL { 
    ?uri gs:icon ?icon .
    ?icon gs:url ?iconUrl .
  } .
}
