PREFIX gs: <ips://galacteek.ld/>
PREFIX h: <ips://galacteek.ld/Hashmark#>
PREFIX tag: <ips://galacteek.ld/Tag#>

PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?uri ?tagName ?tagDisplayName
       ?tagPriority ?tagDateCreated
       ?tagShortDescription
       ?tagAbstract
       (GROUP_CONCAT(?meaningUrl; SEPARATOR=";") as ?meanings)
WHERE {
  ?uri a gs:Tag .
  ?uri tag:name ?tagName .

  OPTIONAL {
    ?uri tag:displayName ?tagDisplayName .
    FILTER (langMatches(lang(?tagDisplayName), str(?langTag)))
  } .

  OPTIONAL {
    ?uri tag:priority ?tagPriority .
  } .

  OPTIONAL {
    ?uri tag:hasMeaning ?meaningUrl .
    OPTIONAL {
      ?meaningUrl dbo:abstract ?tagAbstract .
      FILTER (langMatches(lang(?tagAbstract), str(?langTag)))
    } .
  } .

  OPTIONAL {
    ?uri tag:shortDescription ?tagShortDescription .
    FILTER (langMatches(lang(?tagShortDescription), str(?langTag)))
  } .

  OPTIONAL {
    ?uri tag:dateCreated ?tagDateCreated .
  } .

  FILTER (langMatches(lang(?tagName), str("*")))
}

GROUP BY ?uri
ORDER BY ASC(?uri)
