PREFIX gs: <ips://galacteek.ld/>
PREFIX tag: <ips://galacteek.ld/Tag#>
PREFIX tagmgr: <ips://galacteek.ld/TagPreferencesManager#>

SELECT ?uri ?tagWatched ?tagName ?tagDisplayName
WHERE {
  ?uri a gs:TagPreferencesManager .

  ?uri tagmgr:watchTag ?tagWatched .
  ?tagWatched tag:name ?tagName .

  OPTIONAL {
    ?tagWatched tag:displayName ?tagDisplayName .
    FILTER(LANG(?tagDisplayName) = str(?langTagMatch))
  } .
}
