#!/bin/bash

HERE=$(dirname $(readlink -f "${0}"))
SPHERE=/app/lib/python3.7/site-packages

export GALACTEEK_COMMIT_SHA="@@COMMIT_SHA@@"
export XKB_CONFIG_ROOT=/usr/share/X11/xkb
export GALACTEEK_MAGIC_DBPATH=/app/share/file/magic-galacteek.mgc
export SSL_CERT_FILE=${SPHERE}/certifi/cacert.pem

eval export $(galacteek-starter --venv-info)

export PYTHONPATH=${GVENV_SITE_PACKAGES}:${SPHERE}:${PYTHONPATH}

galacteek-starter --from-flatpak "$@"
