envs:
  default:
    publish:
      # Automatically republish local IPID
      autoRepublish: True

      # Republish delay (seconds)
      autoRepublishDelay: 300

      # IPNS publish values (local IPID)
      ipns:
        timeout: 300
        lifetime: '48h'
        ttl: '12h'

    resolve:
      # Timeout in seconds for resolving IPID documents
      timeout: 45

      cacheLifetime:
        # Cache lifetime for DID resolve results (in minutes)
        default:
          minutes: 10

        local:
          minutes: 518400

      # Delay before a resolved IPID is considered "stale", in seconds
      staleDelay: 180
