# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './galacteek/ui/browsertab.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BrowserTabForm(object):
    def setupUi(self, BrowserTabForm):
        BrowserTabForm.setObjectName("BrowserTabForm")
        BrowserTabForm.resize(741, 444)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(BrowserTabForm)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadIpfsHashButton = QtWidgets.QPushButton(BrowserTabForm)
        self.loadIpfsHashButton.setMaximumSize(QtCore.QSize(40, 24))
        self.loadIpfsHashButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/share/icons/ipfs-logo-128-ice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadIpfsHashButton.setIcon(icon)
        self.loadIpfsHashButton.setObjectName("loadIpfsHashButton")
        self.horizontalLayout.addWidget(self.loadIpfsHashButton)
        self.loadIpnsHashButton = QtWidgets.QPushButton(BrowserTabForm)
        self.loadIpnsHashButton.setMaximumSize(QtCore.QSize(40, 24))
        self.loadIpnsHashButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/share/icons/ipfs-logo-128-white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadIpnsHashButton.setIcon(icon1)
        self.loadIpnsHashButton.setObjectName("loadIpnsHashButton")
        self.horizontalLayout.addWidget(self.loadIpnsHashButton)
        self.loadFromClipboardButton = QtWidgets.QPushButton(BrowserTabForm)
        self.loadFromClipboardButton.setMaximumSize(QtCore.QSize(40, 24))
        self.loadFromClipboardButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/share/icons/clipboard-with-pencil-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadFromClipboardButton.setIcon(icon2)
        self.loadFromClipboardButton.setObjectName("loadFromClipboardButton")
        self.horizontalLayout.addWidget(self.loadFromClipboardButton)
        self.urlZone = QtWidgets.QLineEdit(BrowserTabForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlZone.sizePolicy().hasHeightForWidth())
        self.urlZone.setSizePolicy(sizePolicy)
        self.urlZone.setMinimumSize(QtCore.QSize(400, 0))
        self.urlZone.setMaximumSize(QtCore.QSize(1000, 26))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setItalic(False)
        self.urlZone.setFont(font)
        self.urlZone.setObjectName("urlZone")
        self.horizontalLayout.addWidget(self.urlZone)
        self.backButton = QtWidgets.QToolButton(BrowserTabForm)
        self.backButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/share/icons/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon3)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.forwardButton = QtWidgets.QToolButton(BrowserTabForm)
        self.forwardButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/share/icons/right-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forwardButton.setIcon(icon4)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.refreshButton = QtWidgets.QPushButton(BrowserTabForm)
        self.refreshButton.setMaximumSize(QtCore.QSize(50, 24))
        self.refreshButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/share/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon5)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.pinComboBox = QtWidgets.QComboBox(BrowserTabForm)
        self.pinComboBox.setObjectName("pinComboBox")
        self.horizontalLayout.addWidget(self.pinComboBox)
        self.progressBar = QtWidgets.QProgressBar(BrowserTabForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMaximumSize(QtCore.QSize(30, 16777215))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_17.addLayout(self.horizontalLayout_7)
        self.vLayoutBrowser = QtWidgets.QVBoxLayout()
        self.vLayoutBrowser.setObjectName("vLayoutBrowser")
        self.verticalLayout_17.addLayout(self.vLayoutBrowser)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)

        self.retranslateUi(BrowserTabForm)
        QtCore.QMetaObject.connectSlotsByName(BrowserTabForm)

    def retranslateUi(self, BrowserTabForm):
        _translate = QtCore.QCoreApplication.translate
        BrowserTabForm.setWindowTitle(_translate("BrowserTabForm", "Form"))
        self.loadIpfsHashButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Load IPFS hash</p></body></html>"))
        self.loadIpnsHashButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Load IPNS hash/name</p></body></html>"))
        self.loadFromClipboardButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Load IPFS hash from clipboard</p></body></html>"))
        self.backButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Previous</p></body></html>"))
        self.forwardButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Next</p></body></html>"))
        self.refreshButton.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Refresh</p></body></html>"))
        self.pinComboBox.setToolTip(_translate("BrowserTabForm", "<html><head/><body><p>Pin</p></body></html>"))

from . import galacteek_rc
