# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './galacteek/ui/galacteek.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GalacteekWindow(object):
    def setupUi(self, GalacteekWindow):
        GalacteekWindow.setObjectName("GalacteekWindow")
        GalacteekWindow.resize(616, 435)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GalacteekWindow.sizePolicy().hasHeightForWidth())
        GalacteekWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/share/icons/ipfs-logo-128-ice-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GalacteekWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GalacteekWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(3, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openBrowserTabButton = QtWidgets.QPushButton(self.centralwidget)
        self.openBrowserTabButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/share/icons/ipfs-logo-128-ice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openBrowserTabButton.setIcon(icon1)
        self.openBrowserTabButton.setIconSize(QtCore.QSize(32, 32))
        self.openBrowserTabButton.setObjectName("openBrowserTabButton")
        self.horizontalLayout_2.addWidget(self.openBrowserTabButton)
        self.manageKeysButton = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/share/icons/lock-and-key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageKeysButton.setIcon(icon2)
        self.manageKeysButton.setIconSize(QtCore.QSize(32, 32))
        self.manageKeysButton.setObjectName("manageKeysButton")
        self.horizontalLayout_2.addWidget(self.manageKeysButton, 0, QtCore.Qt.AlignLeft)
        self.myFilesButton = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/share/icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.myFilesButton.setIcon(icon3)
        self.myFilesButton.setIconSize(QtCore.QSize(32, 32))
        self.myFilesButton.setObjectName("myFilesButton")
        self.horizontalLayout_2.addWidget(self.myFilesButton, 0, QtCore.Qt.AlignLeft)
        self.bookmarksButton = QtWidgets.QPushButton(self.centralwidget)
        self.bookmarksButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/share/icons/bookmarks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bookmarksButton.setIcon(icon4)
        self.bookmarksButton.setIconSize(QtCore.QSize(32, 32))
        self.bookmarksButton.setObjectName("bookmarksButton")
        self.horizontalLayout_2.addWidget(self.bookmarksButton)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.writeNewDocumentButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeNewDocumentButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/share/icons/write-document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.writeNewDocumentButton.setIcon(icon5)
        self.writeNewDocumentButton.setIconSize(QtCore.QSize(32, 32))
        self.writeNewDocumentButton.setObjectName("writeNewDocumentButton")
        self.horizontalLayout_2.addWidget(self.writeNewDocumentButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBlank = QtWidgets.QWidget()
        self.tabBlank.setObjectName("tabBlank")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabBlank)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget.addTab(self.tabBlank, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        GalacteekWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GalacteekWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 616, 20))
        self.menubar.setObjectName("menubar")
        self.menuVery_Good = QtWidgets.QMenu(self.menubar)
        self.menuVery_Good.setObjectName("menuVery_Good")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        GalacteekWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GalacteekWindow)
        self.statusbar.setObjectName("statusbar")
        GalacteekWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(GalacteekWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddProfile = QtWidgets.QAction(GalacteekWindow)
        self.actionAddProfile.setObjectName("actionAddProfile")
        self.actionShowPeersInformation = QtWidgets.QAction(GalacteekWindow)
        self.actionShowPeersInformation.setObjectName("actionShowPeersInformation")
        self.actionShowIpfsRefs = QtWidgets.QAction(GalacteekWindow)
        self.actionShowIpfsRefs.setObjectName("actionShowIpfsRefs")
        self.actionSettings = QtWidgets.QAction(GalacteekWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuVery_Good.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuVery_Good.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(GalacteekWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GalacteekWindow)

    def retranslateUi(self, GalacteekWindow):
        _translate = QtCore.QCoreApplication.translate
        GalacteekWindow.setWindowTitle(_translate("GalacteekWindow", "Galacteek"))
        self.openBrowserTabButton.setToolTip(_translate("GalacteekWindow", "<html><head/><body><p>Browse</p></body></html>"))
        self.manageKeysButton.setToolTip(_translate("GalacteekWindow", "<html><head/><body><p>IPFS keys</p></body></html>"))
        self.manageKeysButton.setText(_translate("GalacteekWindow", "..."))
        self.myFilesButton.setToolTip(_translate("GalacteekWindow", "<html><head/><body><p>My Files</p></body></html>"))
        self.myFilesButton.setText(_translate("GalacteekWindow", "..."))
        self.bookmarksButton.setToolTip(_translate("GalacteekWindow", "<html><head/><body><p>Bookmarks</p></body></html>"))
        self.writeNewDocumentButton.setToolTip(_translate("GalacteekWindow", "<html><head/><body><p>Write and import new document</p></body></html>"))
        self.menuVery_Good.setTitle(_translate("GalacteekWindow", "File"))
        self.menuEdit.setTitle(_translate("GalacteekWindow", "Edit"))
        self.actionQuit.setText(_translate("GalacteekWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("GalacteekWindow", "Ctrl+Q"))
        self.actionAddProfile.setText(_translate("GalacteekWindow", "Add Profile"))
        self.actionShowPeersInformation.setText(_translate("GalacteekWindow", "Show peers information"))
        self.actionShowIpfsRefs.setText(_translate("GalacteekWindow", "Show refs"))
        self.actionSettings.setText(_translate("GalacteekWindow", "Settings"))

from . import galacteek_rc
