# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './galacteek/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialogForm(object):
    def setupUi(self, SettingsDialogForm):
        SettingsDialogForm.setObjectName("SettingsDialogForm")
        SettingsDialogForm.resize(763, 507)
        self.gridLayout = QtWidgets.QGridLayout(SettingsDialogForm)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialogForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(SettingsDialogForm)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.downloadsLocation = QtWidgets.QLineEdit(self.tab)
        self.downloadsLocation.setObjectName("downloadsLocation")
        self.gridLayout_4.addWidget(self.downloadsLocation, 4, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(280, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.home = QtWidgets.QLineEdit(self.tab)
        self.home.setObjectName("home")
        self.gridLayout_4.addWidget(self.home, 0, 1, 1, 2)
        self.goToHomePageOnOpen = QtWidgets.QCheckBox(self.tab)
        self.goToHomePageOnOpen.setObjectName("goToHomePageOnOpen")
        self.gridLayout_4.addWidget(self.goToHomePageOnOpen, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(391, 262, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.changeDownloadsPathButton = QtWidgets.QPushButton(self.tab)
        self.changeDownloadsPathButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.changeDownloadsPathButton.setObjectName("changeDownloadsPathButton")
        self.gridLayout_4.addWidget(self.changeDownloadsPathButton, 5, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBoxDaemon = QtWidgets.QGroupBox(self.tab_6)
        self.groupBoxDaemon.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxDaemon.setCheckable(True)
        self.groupBoxDaemon.setObjectName("groupBoxDaemon")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxDaemon)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtWidgets.QLabel(self.groupBoxDaemon)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.ipfsdApiPort = QtWidgets.QSpinBox(self.groupBoxDaemon)
        self.ipfsdApiPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ipfsdApiPort.setMinimum(1024)
        self.ipfsdApiPort.setMaximum(32768)
        self.ipfsdApiPort.setObjectName("ipfsdApiPort")
        self.gridLayout_5.addWidget(self.ipfsdApiPort, 1, 1, 1, 1)
        self.ipfsdGwPort = QtWidgets.QSpinBox(self.groupBoxDaemon)
        self.ipfsdGwPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ipfsdGwPort.setMinimum(1024)
        self.ipfsdGwPort.setMaximum(32768)
        self.ipfsdGwPort.setObjectName("ipfsdGwPort")
        self.gridLayout_5.addWidget(self.ipfsdGwPort, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBoxDaemon)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 2, 1, 1)
        self.swarmMinConns = QtWidgets.QSpinBox(self.groupBoxDaemon)
        self.swarmMinConns.setMinimum(1)
        self.swarmMinConns.setMaximum(100)
        self.swarmMinConns.setObjectName("swarmMinConns")
        self.gridLayout_5.addWidget(self.swarmMinConns, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBoxDaemon)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 1, 2, 1, 1)
        self.ipfsdSwarmPort = QtWidgets.QSpinBox(self.groupBoxDaemon)
        self.ipfsdSwarmPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ipfsdSwarmPort.setMinimum(1024)
        self.ipfsdSwarmPort.setMaximum(32768)
        self.ipfsdSwarmPort.setObjectName("ipfsdSwarmPort")
        self.gridLayout_5.addWidget(self.ipfsdSwarmPort, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBoxDaemon)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.swarmMaxConns = QtWidgets.QSpinBox(self.groupBoxDaemon)
        self.swarmMaxConns.setMinimum(10)
        self.swarmMaxConns.setMaximum(300)
        self.swarmMaxConns.setObjectName("swarmMaxConns")
        self.gridLayout_5.addWidget(self.swarmMaxConns, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBoxDaemon)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBoxDaemon)
        self.groupBoxIpfsConn = QtWidgets.QGroupBox(self.tab_6)
        self.groupBoxIpfsConn.setEnabled(True)
        self.groupBoxIpfsConn.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBoxIpfsConn.setFlat(False)
        self.groupBoxIpfsConn.setCheckable(False)
        self.groupBoxIpfsConn.setChecked(False)
        self.groupBoxIpfsConn.setObjectName("groupBoxIpfsConn")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBoxIpfsConn)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBoxIpfsConn)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_16 = QtWidgets.QLabel(self.groupBoxIpfsConn)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.customIpfsApiPort = QtWidgets.QSpinBox(self.groupBoxIpfsConn)
        self.customIpfsApiPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.customIpfsApiPort.setMinimum(1024)
        self.customIpfsApiPort.setMaximum(32768)
        self.customIpfsApiPort.setObjectName("customIpfsApiPort")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.customIpfsApiPort)
        self.label = QtWidgets.QLabel(self.groupBoxIpfsConn)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.customIpfsGwPort = QtWidgets.QSpinBox(self.groupBoxIpfsConn)
        self.customIpfsGwPort.setMaximumSize(QtCore.QSize(100, 16777215))
        self.customIpfsGwPort.setMinimum(1024)
        self.customIpfsGwPort.setMaximum(32768)
        self.customIpfsGwPort.setObjectName("customIpfsGwPort")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.customIpfsGwPort)
        self.customIpfsHost = QtWidgets.QLineEdit(self.groupBoxIpfsConn)
        self.customIpfsHost.setMaximumSize(QtCore.QSize(300, 16777215))
        self.customIpfsHost.setObjectName("customIpfsHost")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.customIpfsHost)
        self.verticalLayout_5.addWidget(self.groupBoxIpfsConn)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(SettingsDialogForm)
        self.tabWidget.setCurrentIndex(1)
        self.buttonBox.accepted.connect(SettingsDialogForm.accept)
        self.buttonBox.rejected.connect(SettingsDialogForm.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogForm)

    def retranslateUi(self, SettingsDialogForm):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialogForm.setWindowTitle(_translate("SettingsDialogForm", "Settings"))
        self.label_3.setText(_translate("SettingsDialogForm", "Home:"))
        self.goToHomePageOnOpen.setText(_translate("SettingsDialogForm", "Go to home page when opening a new browser tab"))
        self.label_7.setText(_translate("SettingsDialogForm", "Save downloads to:"))
        self.changeDownloadsPathButton.setText(_translate("SettingsDialogForm", "Change directory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialogForm", "General"))
        self.groupBoxDaemon.setTitle(_translate("SettingsDialogForm", "Spawn IPFS daemon and use as transport"))
        self.label_17.setText(_translate("SettingsDialogForm", "HTTP gateway port"))
        self.label_18.setText(_translate("SettingsDialogForm", "Minimum swarm connections"))
        self.label_19.setText(_translate("SettingsDialogForm", "Maximum swarm connections"))
        self.label_15.setText(_translate("SettingsDialogForm", "API port"))
        self.label_14.setText(_translate("SettingsDialogForm", "Swarm port"))
        self.groupBoxIpfsConn.setTitle(_translate("SettingsDialogForm", "Use a custom IPFS daemon"))
        self.label_2.setText(_translate("SettingsDialogForm", "Host"))
        self.label_16.setText(_translate("SettingsDialogForm", "API port"))
        self.label.setText(_translate("SettingsDialogForm", "HTTP gateway port"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("SettingsDialogForm", "IPFS"))

