TOPIC_MAIN = 'galacteek.main'
TOPIC_PEERS = 'galacteek.peers'
TOPIC_CHAT = 'galacteek.chat'
TOPIC_ENC_CHAT = 'galacteek.enc.chat'
TOPIC_HASHMARKS = 'galacteek.hashmarks'
TOPIC_DAGEXCH = 'galacteek.dagexchange'
