#!/bin/bash

HERE=$(dirname $(readlink -f "${0}"))

export GALACTEEK_COMMIT_SHA="@@COMMIT_SHA@@"

export FONTCONFIG_FILE=$HERE/usr/etc/fonts/fonts.conf
export FONTCONFIG_PATH=$HERE/usr/etc/fonts/

export PATH=${HERE}/usr/bin:$PATH
export LD_LIBRARY_PATH=${HERE}/usr/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$PYTHONPATH:${HERE}/usr/lib/python3.7/site-packages
export QT_QPA_PLATFORM_PLUGIN_PATH=${HERE}/usr/lib/python3.7/site-packages/PyQt5/Qt5/plugins/platforms
export QT_STYLE_OVERRIDE=Fusion

APPIQT_LIBPATH=${HERE}/usr/lib/python3.7/site-packages/PyQt5/Qt5/lib

if [ ! -z "${container}" ] && [ x"${container}" == x"firejail" ]; then
	# Disable qtwebengine sandboxing if running inside firejail
	export QTWEBENGINE_DISABLE_SANDBOX=1
fi

if [ ! -z ${APPIMAGE_LIBCHECK} ]; then
	_LIBS="$QT_QPA_PLATFORM_PLUGIN_PATH/libqxcb.so \
		$APPIQT_LIBPATH/libQt5*"

	for lib in $_LIBS; do
		echo "ldd check: $lib"
		ldd $lib|grep -i 'not found'
	done
	exit 1
fi

BINARY_PATH=$APPIMAGE
BINARY_NAME=$(basename "$APPIMAGE")

"${HERE}"/usr/bin/python "${HERE}"/usr/bin/galacteek \
	--from-appimage \
	--binary-name="${BINARY_NAME}" --binary-path="${BINARY_PATH}" \
	--no-ssl-verify --no-release-check "$@"
