envs:
  default:
    icapregs:
      # icapsule registries
      # Each registry definition must use a valid URN
      #
      # Regs with lowest priority are loaded first
      #
      # regGraphUri is the URI of the RDF graph where the registry will
      # be stored

      # local:
      #  urn: urn:glk:icapregs:devel:${oc.env:ICAPSULE_REGISTRY_BRANCH}
      #  regUrl: file:///${oc.env:HOME}/icapsule-registry-dev-${oc.env:ICAPSULE_REGISTRY_BRANCH}.yaml
      #  regGraphUri: urn:ipg:icapsules:registries:galacteek:${oc.env:ICAPSULE_REGISTRY_BRANCH}

      #  enabled: True
      #  priority: 100

      gitlab:
        urn: urn:glk:icapregs:galacteek:${oc.env:ICAPSULE_REGISTRY_BRANCH}
        regUrl: https://gitlab.com/galacteek/icapsule-registry/-/releases/continuous-${oc.env:ICAPSULE_REGISTRY_BRANCH}/downloads/icapsule-registry.tar.gz

        regGraphUri: urn:ipg:icapsules:registries:galacteek:${oc.env:ICAPSULE_REGISTRY_BRANCH}

        priority: 0
        enabled: true

    profile:
      manifestsByUri:
        urn:glk:dapps:dvoz:
          install: latest
          autoload: true

          wsSwitchOnLoad: true
